### ISSUE TITLE
Add an option to define a target folder where to put the subset fonts

### ISSUE THREAD

**Issue by nhoizey** [zachleat/glyphhanger#5]
I would like the subset fonts to be created in a target folder different from the source folder where the full TTF is.

I can move the files myself of course, but this would be a little more convenient.

Thanks!

**Comment by nhoizey** [comment]
I tried to look at the code but didn't see where I could add this. If you have any advice, I can try to built it and make a PR.

**Comment by kid4git** [comment]
There is an apparently undocumented `--output` parameter that does just what you want. It works with relative and absolute paths. I detected it in cmd.js.

**Comment by nhoizey** [comment]
@kid4git it works indeed, thanks! 👍

@zachleat should I make a PR to update documentation with this feature, or do you prefer to keep it undocumented for a reason we don't know (yet)?

**Comment by nhoizey** [comment]
I see there was a PR on the filamentgroup repo: https://github.com/filamentgroup/glyphhanger/pull/64

**Comment by zachleat** [comment]
If you port that PR over I will merge it!

**Comment by nhoizey** [comment]
@zachleat done: #9

**Comment by nhoizey** [comment]
PR #9 already merged
